language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - if [ "$CXX" = "gcc" ]; then sudo apt-get -qq install g++-4.8 && export CC="gcc-4.8"; fi

script:
  - mkdir _build && cd _build
  - cmake .. && make
  - ./sn_test

notifications:
  email:
    - matej.grabovsky@gmail.com

