language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - if [ "$CC" = "gcc" ]; then sudo apt-get -qq install gcc-4.9; fi

install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi

script:
  - mkdir _build && cd _build
  - cmake .. && make
  - ./sn_test

notifications:
  email:
    - matej.grabovsky@gmail.com

