language: c

compiler:
  - clang
  - gcc-4.9
  - gcc-5
  - gcc-6
  - gcc-7

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - if [ "$CC" != "clang" ]; then sudo apt-get -qq install $CC; fi

script:
  - mkdir _build && cd _build
  - cmake .. && make
  - ./sn_test

notifications:
  email:
    - matej.grabovsky@gmail.com

