language: c

compiler:
  - gcc
  - clang

cache: apt

install:
  - sudo apt-get install cmake

script:
  - mkdir _build && cd _build
  - cmake ..
  - make
  - ./sn_test

notifications:
  email:
    - matej.grabovsky@gmail.com

