dist: trusty
sudo: required
cache:
  apt: true

compiler:
  - clang
  - gcc-4.9
  - gcc-5
  - gcc-6
  - gcc-7

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - if [ "$CC" != "clang" ]; then sudo apt-get -qq install $CC; fi

install:
  - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
  - tar xvf cmocka-1.1.1.tar.xz && cd cmocka-1.1.1
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make && sudo make install
  - cd ../.. && rm -rf cmocka-1.1.1

script:
  - mkdir _build && cd _build
  - cmake .. && make
  - ./sn_test

notifications:
  email:
    - matej.grabovsky@gmail.com

